### ISSUE TITLE
Sdf font error on initialState

### ISSUE THREAD

**Issue by pecoram** [lightning-js/renderer#182]
Is it normal that I get this error when the font is loading?
![image](https://github.com/lightning-js/renderer/assets/33352553/30ac4f9b-41e4-438c-aad1-952d427acaf9)

probably needs to be revised this point otherwise it will always give error when status is loading

https://github.com/lightning-js/renderer/blob/5500bc9092783ece3188a2f14ed9538b475d4d2f/src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts#L376

**Comment by chiefcll** [comment]
@pecoram - I think this is due to recent change in Solid where before we weren't passing in fontWeight + fontStyle. Now that we are it's important to note that `Fonts = Name + Weight + Style` - Each time you change fontWeight you need a corresponding font file.

```
stage.fontManager.addFontFace(
      new SdfTrFontFace(
        'WorkSans',
        { weight: 400 },
        'msdf',
        stage,
        basePath + 'fonts/WorkSans-Regular.msdf.png',
        basePath + 'fonts/WorkSans-Regular.msdf.json',
      ),
    );
    stage.fontManager.addFontFace(
      new SdfTrFontFace(
        'WorkSans',
        { weight: 600 },
        'msdf',
        stage,
        basePath + 'fonts/WorkSans-Medium.msdf.png',
        basePath + 'fonts/WorkSans-Medium.msdf.json',
      ),
    );
    
 ```
 
 However one change we should have in the renderer is to have one font file cover multiple fontWeights - or specify a fallback if it's not loaded with a better error message around Family + Weight + Style requested

**Comment by pecoram** [comment]
I tried but the error is still there. If you don't skip that peace of code it will always give the error message as long as the state is loading
