### ISSUE TITLE
Bug: incorrect app scaling

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#247]
## Problem

There seem to be some confusion internally around `deviceLogicalPixelRatio` and `devicePhysicalPixelRatio`.

Current code:
```js
const deviceLogicalWidth = appWidth * deviceLogicalPixelRatio;
canvas.width = deviceLogicalWidth * devicePhysicalPixelRatio;
canvas.style.width = `${deviceLogicalWidth}px`;
```

Correct code:
```js
canvas.width = appWidth * devicePhysicalPixelRatio;
canvas.style.width = `${appWidth}px`;
```
e.g. `canvas.width` is multiplied by the screen dpi, and `canvas.style.width` sets it to the requested `appWidth`. The canvas shouldn't be affected by `deviceLogicalPixelRatio` at all.

## Validation

The test for correct configuration is: to support a 720p device, we need to request:
- width: 1280
- height: 720
- deviceLogicalPixelRatio: 2/3 (so 1080p coordinates are correct).

Note: fixing the above calculations provide the right canvas size and app scaling, but activation bounds are incorrect.

**Comment by frank-weindel** [comment]
The `appWidth` needs to be multiplied by the deviceLogicalPixelRatio. If an app is authored at 1280x720, then the deviceLogicalPixelRatio must be 1.5 to scale up to a logical (CSS pixel) grid of 1920x1080. The devicePhysicalPixelRatio is used only for displays that represent 1 CSS pixel with multiple sub-pixels, such as an Apple retina display. Generally that is provided directly by `window.devicePixelRatio`, unless overrided.

These ratios are purposefully different than in Lightning 2 so that users can clearly define the width/height they will author their app in, and then the ratios are used to scale that up or down as necessary.

<img width="1272" alt="Screen Shot 2024-04-15 at 12 25 21 PM" src="https://github.com/lightning-js/renderer/assets/6070611/17bfb85a-0ffc-4787-a515-506115e1548c">

**Comment by elsassph** [comment]
Sorry but we author (and designers work) in 1080p, is there a way to keep working with a 1080p référence?

**Comment by frank-weindel** [comment]
Sure. You can set appWidth/appHeight to whatever you are authoring your app at. Then just use the `deviceLogicalPixelRatio` to adjust to the target device resolution:
```
const targetDeviceHeight = 720;
const settings = {
  appWidth: 1920,
  appHeight: 1080
  deviceLogicalPixelRatio: targetDeviceHeight / 1080
}
```

**Comment by frank-weindel** [comment]
Yeah I always thought that method was confusing as it wasn't clear without doing calculations what the authoring resolution was. Many devs may only ever author at 1920x1080 and not really think about it, but there are definitely use cases where other authoring resolutions are needed.
