### ISSUE TITLE
DOMException: A network error occurred while loading sans-serif font face

### ISSUE THREAD

**Issue by suresh-gangumalla** [lightning-js/renderer#284]
Observed an exception while loading sans-serif as default font face.
![renderer-sans-serfi-error](https://github.com/lightning-js/renderer/assets/80351497/9cc13641-fa76-45a4-a69f-3069bd736c1b)

https://github.com/lightning-js/renderer/blob/main/src/core/text-rendering/renderers/CanvasTextRenderer.ts#L148

**Comment by uguraslan** [comment]
It appears that the variable `fontUrlWithoutParentheses`, as defined [here](https://github.com/lightning-js/renderer/blob/68d27910a1581770f5bb418f2d9a61b7eb9dd814/src/core/text-rendering/font-face-types/WebTrFontFace.ts#L67), is assigned an empty string when using the default `sans-serif` font. So the `fontFace.load()` method, called [here](https://github.com/lightning-js/renderer/blob/68d27910a1581770f5bb418f2d9a61b7eb9dd814/src/core/text-rendering/font-face-types/WebTrFontFace.ts#L72), tries to load a font from this URL, resulting in a failure since the URL is an empty string.

The `FontFace` constructor requires the `source` parameter to be either a valid URL or binary font face data.

**Comment by suresh-gangumalla** [comment]
@wouterlucas 
the issue is still reproducing. I have verified this against latest dev branch,  1.0.0-rc.3. 

<img width="956" alt="font-1" src="https://github.com/lightning-js/renderer/assets/80351497/7832d138-0162-4f31-ac1f-4caad35d2aec">

**Comment by elsassph** [comment]
@wouterlucas I was investigating it and indeed as @suresh-gangumalla pointed out, the `CanvasTextRenderer` "loads" a default `sans-serif` font using `WebTrFontFace`, but the DOM `FontFace` will throw this error when the URL is empty.

It is harmless in itself but unnecessary. I presume we could avoid calling `FontFace.load` and just flag it as loaded.

**Comment by elsassph** [comment]
Generally canvas font loading needs to be revisited: the systematic call to `globalFontSet.load` is highly problematic IMHO.

**Comment by frank-weindel** [comment]
@elsassph One of the #322 canvas experiments addresses that and provides a path for loading the texture completely synchronously if the font is already loaded.

**Comment by wouterlucas** [comment]
Let's do a temp fix on the current code base until #322 is mature enough to move along.

**Comment by elsassph** [comment]
I'm concerned about whether #322 will progress while Frank is away. Some improvements should be extracted into granular PRs.

**Comment by wouterlucas** [comment]
It will, I just want a stopgap solution in there so that the error is gone and  so we can do our due diligence on #322 

Agree that chopping it up in smaller PRs is a good idea.
