### ISSUE TITLE
Updating out of bound nodes not happening correctly

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#395]
I have some nodes which get created but are off screen. Eventually the parent container moves them onto the screen. They should be updating color but only the text updates color. The node won't allow it's color to be changed, even if I change it through the inspector and it's on screen at this point it won't update. Using Renderer v2.2.0

**Comment by chiefcll** [comment]
PS - Should look like this

<img width="1568" alt="image" src="https://github.com/user-attachments/assets/6f4f2cca-3155-48fd-a8df-883242cf6c96">

functions correctly until you get to number 4/5

**Comment by michielvandergeest** [comment]
Hello @chiefcll, thanks for reporting this issue. We'll look into it. Would you mind providing a minimal example with a direct renderer implementation that clearly demonstrates this issue, so we can easily reproduce it?

Thanks you.

**Comment by chiefcll** [comment]
const node2 = renderer.createNode({
    x: 0,
    y: 0,
    width: 500,
    height: 500,
    color: 0xcc00ffff,
    parent: testRoot,
  });

  const empty2 = renderer.createNode({
    x: 1200,
    y: 0,
    width: 500,
    height: 500,
    color: 0xcc00ffff,
    parent: node2,
  });

  const empty = renderer.createNode({
    x: 2400,
    y: 0,
    width: 500,
    height: 500,
    color: 0xcc00ffff,
    parent: node2,
  });

  setTimeout(() => {
    empty.color = 0x00ff00ff;
    empty2.color = 0x00ff00ff;
    node2.x = -2000;
  }, 1000);

**Comment by wouterlucas** [comment]
Tested your example and that works fine, this is not a renderer issue.

However since you mentioned you where having an issue on your example app, so I took a look and this is what's happening:

- You have a container node that has  `width: 1750px`
- You're moving that container `x: -2050px` once you get at the 5th item
- Renderer marks the container node as out of bounds (correctly) and stops processing it's children to reduce processing.

The previous graph handling would always process the children, even if they where out of bounds. Recent optimization will mark out of bound parts of the render tree as "dead" and only resume processing once they're in bounds or in viewport again.

IMHO your flex engine is incorrectly calculating the width of the container node, if you are adding 11 items that are each `370px` wide your container node (Row?) should be closer to 4070px + whatever gap's you're adding. If you then set that at `x: -2050px` it wouldn't mark the container node as out of bounds and the issue wouldn't happen.

**Comment by wouterlucas** [comment]
Also https://github.com/lightning-js/renderer/pull/399 should help you debug more easily

**Comment by elsassph** [comment]
@wouterlucas it sounds like there is an inconsistency:
- children are considered inactive, so their textures don't update,
- but children still render.

Maybe inactive nodes shouldn't render, so at least it would be easier to understand what is going on.

**Comment by wouterlucas** [comment]
Fair, another optimization would be to not upload quads for inactive nodes and I agree that would make the behaviour more consistent. I think the only condition that is being evaluated right now is the alpha value. However this could easily include the renderState stuff like view port / boundary status.

The "inconsistency" is by design though. Currently there is an `update()` loop and a `draw()` loop each doing their own part. This is because you don't know what to render prior to traversing the tree with pending updates. The `update` loop recently saw some changes because it had a bottleneck or two, whilst the draw / addQuads loop is already quite lean & mean.

**Comment by chiefcll** [comment]
Thanks for the update. Wanted to make sure this was an intentional breaking change from the previous versions. 

Flex is working correctly and according to spec - https://lightning-tv.github.io/solid/#/flow/layout?id=flex-properties - there is a flexBoundary that I'll update to 'contain' as the default rather than fixed. There will also be an update to https://github.com/rdkcentral/solid-ui components to fix withScrolling now that the container size has to match content size.
