### ISSUE TITLE
InViewPort is not calculated based on Window

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#416]
https://github.com/lightning-js/renderer/blob/main/src/core/CoreNode.ts#L1227C4-L1229C6

InViewPort is being calculated based off Parent's bounds. If I have a parent that is bigger than the window size the node is considered InViewPort even though it is offscreen. 
{x1: 0, y1: 660, x2: 1920, y2: 1240} - (node at y: 660 with height: 580 - put a child in it at y: 1100)

Opening for discussion for should InViewPort always use bounds of the Window / Canvas? (1920x1080)

**Comment by wouterlucas** [comment]
There's two strategies for this:
* Cap the bounds of a clipping enabled parent to the stage width/height. Downside is we'll have to update all the children if you move the parent which would retrigger a boundary recalculation for all its children down the tree
* Add an additional statement in the individual node bound detection to see if we're outside of the stage width/height regardless of the parent boundaries. 

I'd lean towards option 2, it might be a little impact on each update check but provide a more consistent behaviour, just need to think through all of the implications.

**Comment by chiefcll** [comment]
#2 is fine. I think the isInViewPort has a special meaning that should always be based off the Canvas size.

When you update this could you also add a public helper like

`isInViewPort(): boolean` - I know there are events but I'd like to query it on demand in some cases.

**Comment by wouterlucas** [comment]
Isn't `public renderState` available? That should give you all the status, else we can make a nice getter around it.

**Comment by chiefcll** [comment]
I think the getters are necessary or you need to export CoreNodeRenderState.

**Comment by wouterlucas** [comment]
Ah so this only happens when clipping is enabled on the parent, please try if #423 fixes it for you

**Comment by wouterlucas** [comment]
So circling back to this, I think #423 fixes your issue when clipping is enabled and I've described the issue in #426. What happened is that every node that had clipping enabled recalculated its boundaries, but ignored its own boundary when out of viewport. This has been resolved as such that we only apply that boundary if its in viewport. Can likely simplify it a little bit by leveraging the clipping rect instead of doing manual checks. 

However the idea of only window / stage boundaries is not going to work, the events also need to be fired when a node exits the visible area due to clipping and rendering boundaries can be applied accordingly.

Closing this and continuing on https://github.com/lightning-js/renderer/issues/426
